services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzamaker
      MYSQL_USER: user
      MYSQL_PASSWORD: pizzamaker
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ../migrations:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
