server:
  port: 8080

local:
  fe-host: "http://localhost:3000"

database:
  host: "localhost"
  port: 3306
  username: "user"
  password: "pizzamaker"
  dbName: "pizzamaker"

grpc:
  host: "localhost"
  port: 50051
