name: Build and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test -v ./internal/...

      - name: Run integration tests
        run: go test -v ./test/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          DOCKER_HOST: unix:///var/run/docker.sock
